# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 557)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(220, 10, 731, 541))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalSliderCutOffFreq = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSliderCutOffFreq.setGeometry(QtCore.QRect(10, 50, 191, 22))
        self.horizontalSliderCutOffFreq.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCutOffFreq.setObjectName("horizontalSliderCutOffFreq")
        self.pushButtonOriginalSound = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOriginalSound.setGeometry(QtCore.QRect(10, 490, 191, 23))
        self.pushButtonOriginalSound.setObjectName("pushButtonOriginalSound")
        self.labelCutOffFreq = QtWidgets.QLabel(self.centralwidget)
        self.labelCutOffFreq.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.labelCutOffFreq.setObjectName("labelCutOffFreq")
        self.labelCutOffFreqValue = QtWidgets.QLabel(self.centralwidget)
        self.labelCutOffFreqValue.setGeometry(QtCore.QRect(120, 20, 91, 16))
        self.labelCutOffFreqValue.setObjectName("labelCutOffFreqValue")
        self.pushButtonLowPassSound = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLowPassSound.setGeometry(QtCore.QRect(10, 520, 191, 23))
        self.pushButtonLowPassSound.setObjectName("pushButtonLowPassSound")
        self.pushButtonDrawGraph = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDrawGraph.setGeometry(QtCore.QRect(10, 80, 191, 23))
        self.pushButtonDrawGraph.setObjectName("pushButtonDrawGraph")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Low Pass Filter"))
        self.pushButtonOriginalSound.setText(_translate("MainWindow", "Play Original Sound"))
        self.labelCutOffFreq.setText(_translate("MainWindow", "Cut Off Frequency"))
        self.labelCutOffFreqValue.setText(_translate("MainWindow", "0"))
        self.pushButtonLowPassSound.setText(_translate("MainWindow", "Play Low Passed Sound"))
        self.pushButtonDrawGraph.setText(_translate("MainWindow", "Draw New Graph"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
